// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJei6VS4MeD30SniTB4zglRLfVAQHMpo',
    appId: '1:703417438352:web:3da66777d6d98e4cffc815',
    messagingSenderId: '703417438352',
    projectId: 'app-ddm-ryan',
    authDomain: 'app-ddm-ryan.firebaseapp.com',
    storageBucket: 'app-ddm-ryan.appspot.com',
    measurementId: 'G-Y1ME1SFD1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6jBI-SNdkK8sjQWjcmVsB9Net8deiPZE',
    appId: '1:703417438352:android:471205ea1cfc6ee8ffc815',
    messagingSenderId: '703417438352',
    projectId: 'app-ddm-ryan',
    storageBucket: 'app-ddm-ryan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4-yQYnJ5-YeyV1Mzk9Fnmlt8G71bfMYY',
    appId: '1:703417438352:ios:91f957f5ec5c6347ffc815',
    messagingSenderId: '703417438352',
    projectId: 'app-ddm-ryan',
    storageBucket: 'app-ddm-ryan.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4-yQYnJ5-YeyV1Mzk9Fnmlt8G71bfMYY',
    appId: '1:703417438352:ios:91f957f5ec5c6347ffc815',
    messagingSenderId: '703417438352',
    projectId: 'app-ddm-ryan',
    storageBucket: 'app-ddm-ryan.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFJei6VS4MeD30SniTB4zglRLfVAQHMpo',
    appId: '1:703417438352:web:d90aa91da2603e03ffc815',
    messagingSenderId: '703417438352',
    projectId: 'app-ddm-ryan',
    authDomain: 'app-ddm-ryan.firebaseapp.com',
    storageBucket: 'app-ddm-ryan.appspot.com',
    measurementId: 'G-QCDL13CY2P',
  );
}
