// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeCYfIFHt2rnrLZPWj0yz9_n7TXcbmPU0',
    appId: '1:116590503471:web:a1156da760dc5d64bf48da',
    messagingSenderId: '116590503471',
    projectId: 'ddm-icoma',
    authDomain: 'ddm-icoma.firebaseapp.com',
    storageBucket: 'ddm-icoma.appspot.com',
    measurementId: 'G-Z87Q9LM61M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLilx666-iEaWZljxk1NTcOzuatKH8TnI',
    appId: '1:116590503471:android:9f83d20e39699842bf48da',
    messagingSenderId: '116590503471',
    projectId: 'ddm-icoma',
    storageBucket: 'ddm-icoma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG1CvNv6NE44uOOt4YSfSTadUiikdVqXk',
    appId: '1:116590503471:ios:6422bfd71eda8472bf48da',
    messagingSenderId: '116590503471',
    projectId: 'ddm-icoma',
    storageBucket: 'ddm-icoma.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG1CvNv6NE44uOOt4YSfSTadUiikdVqXk',
    appId: '1:116590503471:ios:6422bfd71eda8472bf48da',
    messagingSenderId: '116590503471',
    projectId: 'ddm-icoma',
    storageBucket: 'ddm-icoma.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeCYfIFHt2rnrLZPWj0yz9_n7TXcbmPU0',
    appId: '1:116590503471:web:9f0318b677a6ee7dbf48da',
    messagingSenderId: '116590503471',
    projectId: 'ddm-icoma',
    authDomain: 'ddm-icoma.firebaseapp.com',
    storageBucket: 'ddm-icoma.appspot.com',
    measurementId: 'G-LRVQ6E6H8E',
  );
}
