// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9rQHDpC0ikT4LtAZLb4M3hwnwUctERI',
    appId: '1:899955809719:web:bfb514374bba77bb4a1c32',
    messagingSenderId: '899955809719',
    projectId: 'app-ddm-justimiano',
    authDomain: 'app-ddm-justimiano.firebaseapp.com',
    storageBucket: 'app-ddm-justimiano.appspot.com',
    measurementId: 'G-W77V23CNHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3lnOBatQzmYO8ZjC9viSH3W2IVa76YXo',
    appId: '1:899955809719:android:20abc35d27829c214a1c32',
    messagingSenderId: '899955809719',
    projectId: 'app-ddm-justimiano',
    storageBucket: 'app-ddm-justimiano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm6-iXdFEeo4Cfip7w6rcKhbHBdVeHka0',
    appId: '1:899955809719:ios:22f520749d8059904a1c32',
    messagingSenderId: '899955809719',
    projectId: 'app-ddm-justimiano',
    storageBucket: 'app-ddm-justimiano.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm6-iXdFEeo4Cfip7w6rcKhbHBdVeHka0',
    appId: '1:899955809719:ios:22f520749d8059904a1c32',
    messagingSenderId: '899955809719',
    projectId: 'app-ddm-justimiano',
    storageBucket: 'app-ddm-justimiano.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp9rQHDpC0ikT4LtAZLb4M3hwnwUctERI',
    appId: '1:899955809719:web:68c7a5d5218653a64a1c32',
    messagingSenderId: '899955809719',
    projectId: 'app-ddm-justimiano',
    authDomain: 'app-ddm-justimiano.firebaseapp.com',
    storageBucket: 'app-ddm-justimiano.appspot.com',
    measurementId: 'G-3XDGFE3TVD',
  );
}
