// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDltra21wWCj-DTSxRbRHEOPoal6xeVHPs',
    appId: '1:982082822407:web:394d9ef8b6fd42f889e5a2',
    messagingSenderId: '982082822407',
    projectId: 'app-ddm-lorrainy',
    authDomain: 'app-ddm-lorrainy.firebaseapp.com',
    storageBucket: 'app-ddm-lorrainy.appspot.com',
    measurementId: 'G-CXCQPTKQQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAL4OttoESavseJHi-PGTIrPVMtyXqM0s',
    appId: '1:982082822407:android:f6692b5cba8d27d489e5a2',
    messagingSenderId: '982082822407',
    projectId: 'app-ddm-lorrainy',
    storageBucket: 'app-ddm-lorrainy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwVlDeBNvuds7yAqqanJqbZqulRZ5QLhE',
    appId: '1:982082822407:ios:6d01f83b62282a4d89e5a2',
    messagingSenderId: '982082822407',
    projectId: 'app-ddm-lorrainy',
    storageBucket: 'app-ddm-lorrainy.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwVlDeBNvuds7yAqqanJqbZqulRZ5QLhE',
    appId: '1:982082822407:ios:6d01f83b62282a4d89e5a2',
    messagingSenderId: '982082822407',
    projectId: 'app-ddm-lorrainy',
    storageBucket: 'app-ddm-lorrainy.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDltra21wWCj-DTSxRbRHEOPoal6xeVHPs',
    appId: '1:982082822407:web:4feba89a6b011eb889e5a2',
    messagingSenderId: '982082822407',
    projectId: 'app-ddm-lorrainy',
    authDomain: 'app-ddm-lorrainy.firebaseapp.com',
    storageBucket: 'app-ddm-lorrainy.appspot.com',
    measurementId: 'G-D9E72K7Z0J',
  );
}
