// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs4Ck9Q6jovng8zqnL7kT0ZozRctkZyMw',
    appId: '1:990076395417:web:e094e375212d1f9b95bd08',
    messagingSenderId: '990076395417',
    projectId: 'app-ddm-b-kenedi',
    authDomain: 'app-ddm-b-kenedi.firebaseapp.com',
    storageBucket: 'app-ddm-b-kenedi.appspot.com',
    measurementId: 'G-46FVMRT6EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlV1xpIG07-W9rIV_TeTjjJPKOaMM0QME',
    appId: '1:990076395417:android:2d22f441f863bca695bd08',
    messagingSenderId: '990076395417',
    projectId: 'app-ddm-b-kenedi',
    storageBucket: 'app-ddm-b-kenedi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX_s8VOElJ1m1fj7cVXQEvWDXxKVcVk_w',
    appId: '1:990076395417:ios:68db08a28d05824c95bd08',
    messagingSenderId: '990076395417',
    projectId: 'app-ddm-b-kenedi',
    storageBucket: 'app-ddm-b-kenedi.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX_s8VOElJ1m1fj7cVXQEvWDXxKVcVk_w',
    appId: '1:990076395417:ios:68db08a28d05824c95bd08',
    messagingSenderId: '990076395417',
    projectId: 'app-ddm-b-kenedi',
    storageBucket: 'app-ddm-b-kenedi.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs4Ck9Q6jovng8zqnL7kT0ZozRctkZyMw',
    appId: '1:990076395417:web:098d07c33070f3a595bd08',
    messagingSenderId: '990076395417',
    projectId: 'app-ddm-b-kenedi',
    authDomain: 'app-ddm-b-kenedi.firebaseapp.com',
    storageBucket: 'app-ddm-b-kenedi.appspot.com',
    measurementId: 'G-3BG5NPE3XD',
  );
}
