// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1J7nfkU_aPp2Vx43pzmbsNtPtmFsmneg',
    appId: '1:525141874009:web:400d568b62d6998835a848',
    messagingSenderId: '525141874009',
    projectId: 'app-ddm-mayara',
    authDomain: 'app-ddm-mayara.firebaseapp.com',
    storageBucket: 'app-ddm-mayara.firebasestorage.app',
    measurementId: 'G-593NNX6NKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcqY17tvQMB6lwGx4BrDcRaN-aA-aPJA0',
    appId: '1:525141874009:android:05568d7e2d0a888d35a848',
    messagingSenderId: '525141874009',
    projectId: 'app-ddm-mayara',
    storageBucket: 'app-ddm-mayara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBedn0ft0gkRVDFCzihTAui_Amx3S5E5HY',
    appId: '1:525141874009:ios:d7edd7ce34703b7c35a848',
    messagingSenderId: '525141874009',
    projectId: 'app-ddm-mayara',
    storageBucket: 'app-ddm-mayara.firebasestorage.app',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBedn0ft0gkRVDFCzihTAui_Amx3S5E5HY',
    appId: '1:525141874009:ios:d7edd7ce34703b7c35a848',
    messagingSenderId: '525141874009',
    projectId: 'app-ddm-mayara',
    storageBucket: 'app-ddm-mayara.firebasestorage.app',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1J7nfkU_aPp2Vx43pzmbsNtPtmFsmneg',
    appId: '1:525141874009:web:441f4c37e05744c935a848',
    messagingSenderId: '525141874009',
    projectId: 'app-ddm-mayara',
    authDomain: 'app-ddm-mayara.firebaseapp.com',
    storageBucket: 'app-ddm-mayara.firebasestorage.app',
    measurementId: 'G-FL8D1NKN0W',
  );

}