// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQTv9ZoxfBGxHFmfwLwWw4yCOUKe2G-s',
    appId: '1:892026564598:web:a2e27d7eda31549fd8e1d7',
    messagingSenderId: '892026564598',
    projectId: 'app-ddm-b-3ff26',
    authDomain: 'app-ddm-b-3ff26.firebaseapp.com',
    storageBucket: 'app-ddm-b-3ff26.appspot.com',
    measurementId: 'G-E814X5NZ9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmXtN99Zi6qjJ8jjn5B1arFUNeLfUAHPY',
    appId: '1:892026564598:android:2d6e491b0b0eb5b0d8e1d7',
    messagingSenderId: '892026564598',
    projectId: 'app-ddm-b-3ff26',
    storageBucket: 'app-ddm-b-3ff26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2DNhOOQBCDC0FJWlTdK_XR0m1nEa1WM0',
    appId: '1:892026564598:ios:87b7bd30b65a1b91d8e1d7',
    messagingSenderId: '892026564598',
    projectId: 'app-ddm-b-3ff26',
    storageBucket: 'app-ddm-b-3ff26.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2DNhOOQBCDC0FJWlTdK_XR0m1nEa1WM0',
    appId: '1:892026564598:ios:87b7bd30b65a1b91d8e1d7',
    messagingSenderId: '892026564598',
    projectId: 'app-ddm-b-3ff26',
    storageBucket: 'app-ddm-b-3ff26.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPQTv9ZoxfBGxHFmfwLwWw4yCOUKe2G-s',
    appId: '1:892026564598:web:8246d7cd7d4dfe1bd8e1d7',
    messagingSenderId: '892026564598',
    projectId: 'app-ddm-b-3ff26',
    authDomain: 'app-ddm-b-3ff26.firebaseapp.com',
    storageBucket: 'app-ddm-b-3ff26.appspot.com',
    measurementId: 'G-06HY2NDW5R',
  );
}
