// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwJ2vxTScwHYVtsGEkclDiK9WaL1Pnj7M',
    appId: '1:910044916080:web:822142ecd838c4109387b5',
    messagingSenderId: '910044916080',
    projectId: 'app-ddm-miquelino',
    authDomain: 'app-ddm-miquelino.firebaseapp.com',
    storageBucket: 'app-ddm-miquelino.appspot.com',
    measurementId: 'G-G6TNVJ7ML8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEuxViGMM4_rtkGUYS7z5JB8RDgpbaMfE',
    appId: '1:910044916080:android:4001285bb225bb319387b5',
    messagingSenderId: '910044916080',
    projectId: 'app-ddm-miquelino',
    storageBucket: 'app-ddm-miquelino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHgn1ATp06xO9vRm3iU0YXOGCeXYTcas',
    appId: '1:910044916080:ios:d4fedf6681b732ac9387b5',
    messagingSenderId: '910044916080',
    projectId: 'app-ddm-miquelino',
    storageBucket: 'app-ddm-miquelino.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHgn1ATp06xO9vRm3iU0YXOGCeXYTcas',
    appId: '1:910044916080:ios:d4fedf6681b732ac9387b5',
    messagingSenderId: '910044916080',
    projectId: 'app-ddm-miquelino',
    storageBucket: 'app-ddm-miquelino.appspot.com',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwJ2vxTScwHYVtsGEkclDiK9WaL1Pnj7M',
    appId: '1:910044916080:web:95cc7e955a0986ca9387b5',
    messagingSenderId: '910044916080',
    projectId: 'app-ddm-miquelino',
    authDomain: 'app-ddm-miquelino.firebaseapp.com',
    storageBucket: 'app-ddm-miquelino.appspot.com',
    measurementId: 'G-T7D0KBD8BX',
  );
}
