// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIcsrDXPWo_2tFIB714nY276Q_HfWO6U4',
    appId: '1:848359995895:web:d73dbd9fa56c47ab8396f2',
    messagingSenderId: '848359995895',
    projectId: 'app-ddm-natalia',
    authDomain: 'app-ddm-natalia.firebaseapp.com',
    storageBucket: 'app-ddm-natalia.firebasestorage.app',
    measurementId: 'G-H0D5Z1LJT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5H2tT0xFnuX3zFg7__xImPQTP3ffLCRQ',
    appId: '1:848359995895:android:b4d06405a52e326b8396f2',
    messagingSenderId: '848359995895',
    projectId: 'app-ddm-natalia',
    storageBucket: 'app-ddm-natalia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWLMixhSySsxD8YVHF9cMhMuuLVy3_t8',
    appId: '1:848359995895:ios:99b01695252032cd8396f2',
    messagingSenderId: '848359995895',
    projectId: 'app-ddm-natalia',
    storageBucket: 'app-ddm-natalia.firebasestorage.app',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAWLMixhSySsxD8YVHF9cMhMuuLVy3_t8',
    appId: '1:848359995895:ios:99b01695252032cd8396f2',
    messagingSenderId: '848359995895',
    projectId: 'app-ddm-natalia',
    storageBucket: 'app-ddm-natalia.firebasestorage.app',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIcsrDXPWo_2tFIB714nY276Q_HfWO6U4',
    appId: '1:848359995895:web:214ca734a20b2a1b8396f2',
    messagingSenderId: '848359995895',
    projectId: 'app-ddm-natalia',
    authDomain: 'app-ddm-natalia.firebaseapp.com',
    storageBucket: 'app-ddm-natalia.firebasestorage.app',
    measurementId: 'G-HCHFSV8KPS',
  );

}