// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJYgZpgWGkAad_DUOdB9ts88IKkDJMpEc',
    appId: '1:707684841394:web:72817d0427e92329a2d6ab',
    messagingSenderId: '707684841394',
    projectId: 'app-ddm-luna',
    authDomain: 'app-ddm-luna.firebaseapp.com',
    storageBucket: 'app-ddm-luna.firebasestorage.app',
    measurementId: 'G-7TRF3FS1S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFXJ-TxAxGXlzdcrUR9BPMo54zFPd2YiU',
    appId: '1:707684841394:android:fd674343b9e69f4aa2d6ab',
    messagingSenderId: '707684841394',
    projectId: 'app-ddm-luna',
    storageBucket: 'app-ddm-luna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2y10LRjE26rJOydlb8Intzxi5DvcKqns',
    appId: '1:707684841394:ios:f6f3169ed8fdbeb7a2d6ab',
    messagingSenderId: '707684841394',
    projectId: 'app-ddm-luna',
    storageBucket: 'app-ddm-luna.firebasestorage.app',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2y10LRjE26rJOydlb8Intzxi5DvcKqns',
    appId: '1:707684841394:ios:f6f3169ed8fdbeb7a2d6ab',
    messagingSenderId: '707684841394',
    projectId: 'app-ddm-luna',
    storageBucket: 'app-ddm-luna.firebasestorage.app',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJYgZpgWGkAad_DUOdB9ts88IKkDJMpEc',
    appId: '1:707684841394:web:aa598aeba9962de1a2d6ab',
    messagingSenderId: '707684841394',
    projectId: 'app-ddm-luna',
    authDomain: 'app-ddm-luna.firebaseapp.com',
    storageBucket: 'app-ddm-luna.firebasestorage.app',
    measurementId: 'G-JGEPY1LQP5',
  );

}